### ISSUE TITLE
System.ArgumentException with similar URI templates

### ISSUE THREAD

**Issue by cecilphillip** [paulcbetts/refit#147]
```csharp
  internal interface IKissMetricsApiInternal
    { 
         [Get("")]
        Task<KissCoreResponse> Root([Header("Authorization")] string authorization);
        
        [Get("/accounts")]
        Task<KissApiPagedResponse<Account>> Accounts([Header("Authorization")] string authorization);
        
       [Get("/accounts/{id}")]
        Task<KissApiResponse<Account>> Accounts([AliasAs("id")] string accountid, [Header("Authorization")] string authorization);
   
    }
```

With the above API definition, I get the follow exception when calling the generated client:

```
System.ArgumentExceptionAn item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary(IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Refit.RequestBuilderImplementation..ctor(Type targetInterface, RefitSettings refitSettings) in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs: line 41
   at Refit.RequestBuilderFactory.Create(Type interfaceType, RefitSettings settings) in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs: line 23
   at Refit.RequestBuilder.ForType(RefitSettings settings) in y:\code\paulcbetts\refit\Refit\RequestBuilder.cs: line 35
   at Refit.RestService.For(HttpClient client, RefitSettings settings) in y:\code\paulcbetts\refit\Refit\RestService.cs: line 23
   at TKM.AnalyticsEngine.KissMetrics.KissMetricsClient..ctor(String apiToken, String baseUrl) in KissMetricsClient.cs: line 41
   at TKM.AnalyticsEngine.KissMetrics.KissMetricsClient..ctor(String apiToken) in KissMetricsClient.cs: line 44
   at TKM.AnalyticsEngine.KissMetrics.Tests.KissMetricsClientTests.<Root_Request_Populates_Model>d__0.MoveNext() in KissMetricsClientTests.cs: line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClassc.<<InvokeTestMethodAsync>b__9>d__e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__0.MoveNext() in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.core\Sdk\ExceptionAggregator.cs: line 90
```

If I remove one of the "/account" templates, then the other calls work fine. Am I defining the templates incorrectly?

**Comment by bennor** [comment]
Refit doesn't support method overloading. Change the last method's name to `Account` and it should work for you.

**Comment by cecilphillip** [comment]
That works. Thanks!

**Comment by bennor** [comment]
No problem :smile:

**Comment by avi22228** [comment]
Awesome .. Saved my day 

Thanks for the answer.
